"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.
Day4: 接入 MySQL + DeepSeek API
Day5: 安装 simpleui 后台框架 + 中文配置
"""

import os
from datetime import timedelta
from pathlib import Path

from dotenv import load_dotenv

# 加载 .env（项目根目录）
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 生产环境必须在 .env 中配置 DJANGO_SECRET_KEY；此处 fallback 仅供本地开发。
# 注意：这里必须用 `or` 兜底，不能用 os.getenv 的第二个参数。
# 原因：os.getenv(key, default) 只在「key 不存在」时返回 default；
# 若环境变量被显式注入为空字符串（例如 docker-compose 的 ${VAR:-} 写法），
# 会返回 ""，绕过兜底并触发 ImproperlyConfigured: The SECRET_KEY setting must not be empty.
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY') or 'django-insecure-local-dev-only-please-change-in-prod'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# 生产环境白名单，逗号分隔；本地开发默认仅允许本机访问
ALLOWED_HOSTS = [h.strip() for h in os.getenv('ALLOWED_HOSTS', '127.0.0.1,localhost').split(',') if h.strip()]

# CORS 配置 — 白名单模式（不放开所有来源）
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    o.strip() for o in os.getenv('CORS_ALLOWED_ORIGINS', 'http://127.0.0.1:8000,http://localhost:8000').split(',') if o.strip()
]


# Application definition
# 注意：unfold 必须放在 django.contrib.admin 之前
INSTALLED_APPS = [
    'corsheaders',
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'drf_spectacular',
    'agent',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 生产化中间件（P0）：请求 ID 注入日志 + 接口限流
    'agent.middleware.RequestIDMiddleware',
    'agent.middleware.MetricsMiddleware',
    'agent.middleware.RateLimitMiddleware',
    # 注意：不要加 GZipMiddleware，会压缩 SSE 流导致逐字节变成大块
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 项目级 templates 优先级最高，用于覆盖 SimpleUI 的 admin/base_site.html（注入品牌 CSS）
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database — 中渔天下 MySQL
# 库名 agent_db，初始化脚本见 agent_db.sql
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME', 'agent_db'),
        'USER': os.getenv('DB_USER', 'root'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        # 本地开发默认 127.0.0.1；Docker/docker-compose 通过 DB_HOST=db 指向数据库服务容器
        'HOST': os.getenv('DB_HOST', '127.0.0.1'),
        'PORT': os.getenv('DB_PORT', '3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization — 默认中文
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

LANGUAGES = [
    ('zh-hans', '简体中文'),
    ('en', 'English'),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

# 说明：Django 5.0 起已移除 USE_L10N（本地化始终随 USE_I18N 开启）。
# 保留此项仅为满足文档/旧配置要求，运行时无实际作用，不会报错。
USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'


# ════════════════════════════════════════════════════════════════
# Django Unfold 后台主题（替代 SimpleUI）
# 设计源：前端「江畔渔火」品牌系统 — 湖青 #1F6B54（主色）/ 渔火橙 #E2703A（强调）
# ════════════════════════════════════════════════════════════════
UNFOLD = {
    # 站点标识（侧栏顶部）
    'SITE_TITLE': '中渔天下',
    'SITE_HEADER': '中渔天下 AI 助手',
    'SITE_SUBHEADER': '后台管理系统',
    'SITE_SYMBOL': 'set_meal',          # 品牌图标（Material Symbols）
    'SITE_URL': '/admin/dashboard/',    # 点击 logo 进入运营看板
    'SHOW_HISTORY': False,

    # 主色（primary）套用品牌「湖青」色阶，覆盖 Unfold 默认紫色
    'COLORS': {
        'primary': {
            '50': '#EAF6F1',
            '100': '#D2E9E0',
            '200': '#A9D4C5',
            '300': '#6FB59E',
            '400': '#3E9078',
            '500': '#1F6B54',
            '600': '#185441',
            '700': '#134435',
            '800': '#0E3328',
            '900': '#09241C',
            '950': '#04130F',
        },
    },

    # 自定义左侧导航（替代 Django 默认 app 列表），与品牌业务分组一致
    'SIDEBAR': {
        'navigation': [
            {
                'title': '运营概览',
                'items': [
                    {'title': '数据看板', 'link': '/admin/dashboard/', 'icon': 'dashboard'},
                ],
            },
            {
                'title': '业务数据',
                'items': [
                    {'title': '产品管理', 'link': '/admin/agent/products/', 'icon': 'category'},
                    {'title': '库存管理', 'link': '/admin/agent/inventory/', 'icon': 'inventory_2'},
                    {'title': '订单管理', 'link': '/admin/agent/orders/', 'icon': 'shopping_cart'},
                ],
            },
            {
                'title': '财务管理',
                'items': [
                    {'title': '公司钱包', 'link': '/admin/agent/wallet/', 'icon': 'account_balance_wallet'},
                    {'title': '收支流水', 'link': '/admin/agent/transaction/', 'icon': 'receipt_long'},
                ],
            },
            {
                'title': '客服与用户',
                'items': [
                    {'title': '用户留言', 'link': '/admin/agent/contactmessage/', 'icon': 'mail'},
                    {'title': '对话记录', 'link': '/admin/agent/conversations/', 'icon': 'forum'},
                    {'title': '定制需求', 'link': '/admin/agent/customrequest/', 'icon': 'playlist_add_check'},
                ],
            },
            {
                'title': '智能问答',
                'items': [
                    {'title': '知识库条目', 'link': '/admin/agent/knowledgechunk/', 'icon': 'menu_book'},
                ],
            },
            {
                'title': '认证与权限',
                'items': [
                    {'title': '用户', 'link': '/admin/auth/user/', 'icon': 'group'},
                    {'title': '用户组', 'link': '/admin/auth/group/', 'icon': 'badge'},
                ],
            },
        ],
    },

    # 注入品牌补充样式（渔火橙强调、看板卡片等）
    'STYLES': ['admin/zy-unfold.css'],
}


# DeepSeek API 配置
DEEPSEEK_API_KEY = os.getenv('DEEPSEEK_API_KEY', '')
DEEPSEEK_BASE_URL = 'https://api.deepseek.com'
DEEPSEEK_MODEL = 'deepseek-chat'


# ──────────────────────────────────────────────────────────────
# 认证（JWT）配置
# ──────────────────────────────────────────────────────────────
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # Swagger/OpenAPI 文档（drf-spectacular）
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': '中渔天下 AI 客服 API',
    'DESCRIPTION': '渔具企业 AI 客服：RAG 检索、ReAct Agent、订单/库存/钱包、JWT 认证',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

SIMPLE_JWT = {
    # access 短（默认 30 分钟）、refresh 长（默认 7 天），走环境变量
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=int(os.getenv('JWT_ACCESS_MINUTES', '30'))),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=int(os.getenv('JWT_REFRESH_DAYS', '7'))),
    # refresh 旋转 + 旋转后旧 refresh 进黑名单（退出/刷新更安全）
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'SIGNING_KEY': os.getenv('JWT_SIGNING_KEY') or SECRET_KEY,
    # ⚠️ 必须用 `or` 而不是 os.getenv('JWT_SIGNING_KEY', SECRET_KEY)。
    # 原因：compose 的 env_file 会把 `.env` 里的 `JWT_SIGNING_KEY=`（空值）
    # 注入成**空字符串**，而 os.getenv(k, default) 只在 key「不存在」时才用 default
    # —— 空字符串会绕过回退，导致 PyJWT 抛 InvalidKeyError: HMAC key must not be empty，
    # 所有登录/签发 token 的接口直接 500。（与 SECRET_KEY 属同一类陷阱，勿改回默认值写法）
}

# 登录失败次数限制（可选加分项）
LOGIN_MAX_ATTEMPTS = int(os.getenv('LOGIN_MAX_ATTEMPTS', '5'))
LOGIN_LOCKOUT_MINUTES = int(os.getenv('LOGIN_LOCKOUT_MINUTES', '15'))


# ════════════════════════════════════════════════════════════════
# 缓存（P0：生产接 Redis；未配置 REDIS_URL 时回退 LocMem，保证本地可跑）
# 登录失败锁定、未来异步任务均依赖此后端。
# ════════════════════════════════════════════════════════════════
REDIS_URL = os.getenv('REDIS_URL')
if REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
            'OPTIONS': {
                'socket_timeout': 2,
                'socket_connect_timeout': 2,
            },
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        }
    }


# ════════════════════════════════════════════════════════════════
# 接口限流（P0：固定窗口，按 用户/IP），详见 agent/middleware.RateLimitMiddleware
# ════════════════════════════════════════════════════════════════
RATE_CHAT_LIMIT = int(os.getenv('RATE_CHAT_LIMIT', '20'))     # 聊天接口每窗口允许次数
RATE_CHAT_WINDOW = int(os.getenv('RATE_CHAT_WINDOW', '60'))   # 窗口秒数
RATE_API_LIMIT = int(os.getenv('RATE_API_LIMIT', '120'))      # 通用 API 每窗口允许次数
RATE_API_WINDOW = int(os.getenv('RATE_API_WINDOW', '60'))

# 对话输入安全审核（默认开启；设为 0/false 关闭，仅保留长度校验）
CONTENT_MODERATION = os.getenv('CONTENT_MODERATION', '1') not in ('0', 'false', 'False', '')


# ════════════════════════════════════════════════════════════════
# 日志（P0：统一格式 + 文件轮转 + request_id 注入，便于生产排障）
# ════════════════════════════════════════════════════════════════
LOG_DIR = BASE_DIR / 'logs'
LOG_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname:<8} {name} [req={request_id}] {message}',
            'style': '{',
        },
    },
    'filters': {
        'request_id': {'()': 'agent.middleware.RequestIDFilter'},
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
            'filters': ['request_id'],
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'zt_agent.log',
            'maxBytes': 10 * 1024 * 1024,   # 10 MB / 文件
            'backupCount': 5,                # 保留 5 个历史文件
            'encoding': 'utf-8',
            'formatter': 'verbose',
            'filters': ['request_id'],
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': os.getenv('LOG_LEVEL', 'INFO'),
    },
    'loggers': {
        'agent': {
            'handlers': ['console', 'file'],
            'level': os.getenv('LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'django': {
            'handlers': ['console', 'file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console', 'file'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}


# ════════════════════════════════════════════════════════════════
# 可观测性：错误上报（可选，不强制依赖 sentry-sdk）
# 配置 SENTRY_DSN 并 pip install sentry-sdk 后自动启用；未配置则跳过。
# ════════════════════════════════════════════════════════════════
SENTRY_DSN = os.getenv('SENTRY_DSN')
if SENTRY_DSN:
    try:
        import sentry_sdk
        from sentry_sdk.integrations.django import DjangoIntegration
        sentry_sdk.init(
            dsn=SENTRY_DSN,
            integrations=[DjangoIntegration()],
            traces_sample_rate=float(os.getenv('SENTRY_TRACES_RATE', '0.1')),
            send_default_pii=False,
            environment=os.getenv('SENTRY_ENV', 'production'),
        )
    except ImportError:
        logging.getLogger(__name__).warning(
            "SENTRY_DSN 已配置但未安装 sentry-sdk，已跳过错误上报（pip install sentry-sdk 启用）"
        )
