# Generated by Django 5.2.17 on 2026-08-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, db_comment='会话ID', max_length=100, null=True)),
                ('role', models.CharField(blank=True, db_comment='user 或 assistant', max_length=20, null=True)),
                ('content', models.TextField(blank=True, db_comment='消息内容', null=True)),
                ('created_at', models.DateTimeField(blank=True, db_comment='时间', null=True)),
            ],
            options={
                'db_table': 'conversations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(blank=True, db_comment='当前库存', null=True)),
                ('alert_line', models.IntegerField(blank=True, db_comment='预警线', null=True)),
            ],
            options={
                'db_table': 'inventory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(db_comment='订单号', max_length=50)),
                ('customer_name', models.CharField(blank=True, db_comment='客户名', max_length=50, null=True)),
                ('product_name', models.CharField(blank=True, db_comment='产品名', max_length=100, null=True)),
                ('quantity', models.IntegerField(blank=True, db_comment='数量', null=True)),
                ('total_price', models.DecimalField(blank=True, db_comment='总价', decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(blank=True, db_comment='状态', max_length=20, null=True)),
                ('created_at', models.DateTimeField(blank=True, db_comment='下单时间', null=True)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_comment='产品名称', max_length=100)),
                ('spec', models.CharField(blank=True, db_comment='规格', max_length=50, null=True)),
                ('target_fish', models.CharField(blank=True, db_comment='适用鱼种', max_length=50, null=True)),
                ('retail_price', models.DecimalField(blank=True, db_comment='零售价', decimal_places=2, max_digits=10, null=True)),
                ('wholesale_price', models.DecimalField(blank=True, db_comment='批发价', decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, db_comment='产品描述', null=True)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('phone', models.CharField(max_length=20, verbose_name='电话')),
                ('message', models.TextField(verbose_name='留言内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
            ],
            options={
                'verbose_name': '用户留言',
                'verbose_name_plural': '用户留言',
                'db_table': 'contact_messages',
            },
        ),
    ]
