# Generated by Django 5.2.17 on 2026-08-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('phone', models.CharField(max_length=20, verbose_name='电话')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='公司名称')),
                ('quantity', models.CharField(max_length=50, verbose_name='需求量')),
                ('description', models.TextField(verbose_name='需求描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
            ],
            options={
                'verbose_name': '定制需求',
                'verbose_name_plural': '定制需求',
                'db_table': 'custom_requests',
            },
        ),
        migrations.AlterModelOptions(
            name='conversations',
            options={'managed': False, 'verbose_name': '对话记录', 'verbose_name_plural': '对话记录'},
        ),
    ]
