# Generated by Django 5.2.17 on 2026-08-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_customrequest_alter_conversations_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='email',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='邮箱'),
        ),
    ]
