# Generated by Django 5.2.17 on 2026-08-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0008_wallet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'managed': False, 'verbose_name': '库存', 'verbose_name_plural': '库存'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'managed': False, 'verbose_name': '订单管理', 'verbose_name_plural': '订单管理'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'managed': False, 'verbose_name': '产品', 'verbose_name_plural': '产品'},
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='提交时间'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否已读'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(db_index=True, max_length=20, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='customrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='提交时间'),
        ),
        migrations.AlterField(
            model_name='customrequest',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否已读'),
        ),
        migrations.AlterField(
            model_name='customrequest',
            name='phone',
            field=models.CharField(db_index=True, max_length=20, verbose_name='电话'),
        ),
    ]
