# Generated by Django 5.2.17 on 2026-09-12 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0009_alter_inventory_options_alter_orders_options_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('phone', models.CharField(blank=True, db_index=True, default='', help_text='绑定后可在个人中心看到该手机号下的历史订单', max_length=20, verbose_name='绑定手机号')),
                ('nickname', models.CharField(blank=True, default='', help_text='下单页会自动带入，可随时修改', max_length=50, verbose_name='收货人姓名')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
                'db_table': 'user_profile',
            },
        ),
    ]
