# Generated by Django 5.2.17 on 2026-09-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0011_orders_user_and_after_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCoordination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(db_index=True, unique=True, verbose_name='商品ID')),
                ('purchase_paused', models.BooleanField(default=False, verbose_name='暂停购买')),
                ('customer_notice', models.TextField(blank=True, null=True, verbose_name='客户提示')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '商品协调覆盖',
                'verbose_name_plural': '商品协调覆盖',
                'db_table': 'product_coordination',
                'managed': True,
            },
        ),
    ]
