# Generated by Django 5.2.17 on 2026-09-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0012_productcoordination'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcoordination',
            name='pause_reason',
            field=models.CharField(blank=True, db_comment='stockout=断货(补货后自动解除) / manual=人工(不自动解除)', default='', max_length=20, verbose_name='暂停原因'),
        ),
    ]
