# Auto-generated by `manage.py inspectdb`, manually cleaned up for agent app.
# managed=False 表示 Django 不负责建表（表已由 agent_db.sql 手动创建）。
from django.db import models


class Products(models.Model):
    name = models.CharField(max_length=100, db_comment='产品名称')
    spec = models.CharField(max_length=50, blank=True, null=True, db_comment='规格')
    target_fish = models.CharField(max_length=50, blank=True, null=True, db_comment='适用鱼种')
    retail_price = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, db_comment='零售价')
    wholesale_price = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, db_comment='批发价')
    description = models.TextField(blank=True, null=True, db_comment='产品描述')

    class Meta:
        managed = False
        db_table = 'products'

    def __str__(self):
        return self.name


class Inventory(models.Model):
    product = models.ForeignKey(Products, models.DO_NOTHING, db_column='product_id', db_comment='对应products.id')
    stock = models.IntegerField(blank=True, null=True, db_comment='当前库存')
    alert_line = models.IntegerField(blank=True, null=True, db_comment='预警线')

    class Meta:
        managed = False
        db_table = 'inventory'

    def __str__(self):
        return f"{self.product.name} 库存 {self.stock}"


class Orders(models.Model):
    order_no = models.CharField(max_length=50, db_comment='订单号')
    customer_name = models.CharField(max_length=50, blank=True, null=True, db_comment='客户名')
    product_name = models.CharField(max_length=100, blank=True, null=True, db_comment='产品名')
    quantity = models.IntegerField(blank=True, null=True, db_comment='数量')
    total_price = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, db_comment='总价')
    status = models.CharField(max_length=20, blank=True, null=True, db_comment='状态')
    created_at = models.DateTimeField(blank=True, null=True, db_comment='下单时间')

    class Meta:
        managed = False
        db_table = 'orders'

    def __str__(self):
        return self.order_no


class Conversations(models.Model):
    session_id = models.CharField(max_length=100, blank=True, null=True, db_comment='会话ID')
    role = models.CharField(max_length=20, blank=True, null=True, db_comment='user 或 assistant')
    content = models.TextField(blank=True, null=True, db_comment='消息内容')
    created_at = models.DateTimeField(blank=True, null=True, db_comment='时间')

    class Meta:
        managed = False
        db_table = 'conversations'
