# Auto-generated by `manage.py inspectdb`, manually cleaned up for agent app.
# managed=False 表示 Django 不负责建表（表已由 agent_db.sql 手动创建）；
# 但字段/索引/约束变更仍可通过 migration 追踪（用 manage.py sqlmigrate 生成 SQL 后手工执行）。
from django.conf import settings
from django.db import models
from django.utils import timezone


# ════════════════════════════════════════════════════════════════
# 状态枚举（TextChoices）
# 用于 Orders.status 等强类型业务字段，避免拼写漂移
# ════════════════════════════════════════════════════════════════
class OrderStatus(models.TextChoices):
    """订单状态机（与旧库'未发货/已发货'字符串兼容）。

    正常流：未发货 →(发货)→ 已发货 →(用户确认收货)→ 已完成
    取消流：未发货 →(取消/超时)→ 已取消
    售后流：已发货/已完成 →(用户申请)→ 退货申请中 →(商家同意)→ 已退货（库存回滚+退款）
                                          └─(商家拒绝)→ 回退到申请前状态
    """
    PENDING   = "未发货", "待发货"        # 已下单、未发货
    SHIPPED   = "已发货", "已发货"        # 已发货（含物流信息）
    COMPLETED = "已完成", "已完成"        # 用户确认收货，交易完结
    RETURNING = "退货申请中", "退货申请中"  # 用户已提交退货申请，待商家处理
    CANCELLED = "已取消", "已取消"        # 客户/商家取消
    RETURNED  = "已退货", "已退货"        # 售后退货（库存已回滚 + 已退款）


class ReturnStatus(models.TextChoices):
    """退货申请的审核结果（与订单状态解耦，便于后台快速筛选待处理申请）。"""
    NONE      = "",        "无"
    PENDING   = "待审核",  "待审核"
    APPROVED  = "已同意",  "已同意"
    REJECTED  = "已拒绝",  "已拒绝"


# ════════════════════════════════════════════════════════════════
# 订单统计口径（**全项目唯一来源**，别再各处自己写 Q(status=...)）
# ════════════════════════════════════════════════════════════════
# 背景：同一个"成交额"曾在三处各写一套 —— 后台看板用全部订单、
# 营销侧用 `status != '已取消'`（把已退货也算进来）、个人中心用
# 已发货+已完成+退货申请中。三个页面报三个数，看起来就是"数据不同步"。
# 统一到下面这组常量，新代码一律引用它们。
#
#   PAID（成交）= 已发货 + 已完成 + 退货申请中
#     · 已发货：物权已转移、钱包已记「订单收入」→ 算成交
#     · 已完成：同上，交易终结 → 算成交
#     · 退货申请中：客户在申请退货，但商家未同意前钱货两未定 → 仍算成交
#       （ZT 个人中心「成交金额」即此口径，营销侧 collect_metrics 与之对齐）
#   CLOSED（终结且不计收入）= 已取消 + 已退货
#   EVER_SHIPPED（曾发货，可能发生退货的集合）= 成交 + 已退货
#     · 退货率的分母必须用它：待发货/已取消的订单永远不可能退货，
#       算进分母会把退货率稀释掉
PAID_ORDER_STATUSES = (
    OrderStatus.SHIPPED, OrderStatus.COMPLETED, OrderStatus.RETURNING,
)
CLOSED_ORDER_STATUSES = (
    OrderStatus.CANCELLED, OrderStatus.RETURNED,
)
EVER_SHIPPED_ORDER_STATUSES = (
    OrderStatus.SHIPPED, OrderStatus.COMPLETED, OrderStatus.RETURNING, OrderStatus.RETURNED,
)


class ConversationRole(models.TextChoices):
    """对话角色：用户消息 vs AI 回复。"""
    USER      = "user",      "用户"
    ASSISTANT = "assistant", "AI 助手"


# ════════════════════════════════════════════════════════════════
# 知识库落库（P2：RAG 知识库数据化）
# 原 KNOWLEDGE_BASE 为 Python 静态语料，改为可在线维护的 DB 表，
# 后台 Admin 直接增删改，RAG 引擎启动时从 DB 构建索引。
# ════════════════════════════════════════════════════════════════
class KnowledgeChunk(models.Model):
    """RAG 知识库条目 — 每条 = 一个问答块（可被切分，title 用于来源标注）"""
    title = models.CharField(max_length=100, db_index=True, verbose_name='标题')
    category = models.CharField(
        max_length=50, default='general', db_index=True,
        verbose_name='分类（季节钓法/鱼种钓法/钓法技巧/企业政策/其他）',
    )
    keywords = models.CharField(
        max_length=255, blank=True, default='',
        verbose_name='检索关键词（逗号分隔）',
    )
    content = models.TextField(verbose_name='内容（回答文本）')
    is_active = models.BooleanField(default=True, db_index=True, verbose_name='启用')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='更新时间')

    class Meta:
        db_table = 'knowledge_chunks'
        verbose_name = '知识库条目'
        verbose_name_plural = '知识库条目'
        indexes = [
            models.Index(fields=['category', 'is_active'], name='idx_kc_cat_active'),
        ]

    def __str__(self):
        return f"{self.title} ({self.category})"


class Products(models.Model):
    name = models.CharField(max_length=100, verbose_name='产品名称', db_comment='产品名称')
    # P0 修复：商品编码（人类可读的唯一标识，替代纯数字 id）
    # 格式建议：SKU-XXXX（如 SKU-0001），由 data migration 为存量数据自动生成
    sku = models.CharField(
        max_length=32, unique=True, db_index=True,
        verbose_name='商品编码',
        db_comment='商品编码（人类可读唯一标识）',
        default='', blank=True,
    )
    spec = models.CharField(max_length=50, blank=True, null=True, verbose_name='规格', db_comment='规格')
    target_fish = models.CharField(
        max_length=50, blank=True, null=True, db_index=True, verbose_name='适用鱼种', db_comment='适用鱼种',
    )
    retail_price = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, verbose_name='零售价', db_comment='零售价')
    wholesale_price = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, verbose_name='批发价', db_comment='批发价')
    description = models.TextField(blank=True, null=True, verbose_name='产品描述', db_comment='产品描述')
    # P0 修复：软删除标志（替代硬删除，下架不丢历史订单关联）
    is_active = models.BooleanField(default=True, db_index=True, verbose_name='是否在售', db_comment='是否在售（软删除）')
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True, verbose_name='创建时间', db_comment='创建时间')
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True, verbose_name='更新时间', db_comment='更新时间')

    class Meta:
        managed = False
        db_table = 'products'
        verbose_name = '产品'
        verbose_name_plural = '产品'

    def __str__(self):
        return f"[{self.sku}] {self.name}" if self.sku else self.name


class Inventory(models.Model):
    product = models.ForeignKey(
        Products, models.PROTECT,  # P0 修复：保护式外键，有库存记录时禁止删除产品
        db_column='product_id', verbose_name='产品',
        db_comment='对应products.id', related_name='inventory',
    )
    # P0 修复：PositiveIntegerField 防止负数；非空默认值确保数据完整性
    stock = models.PositiveIntegerField(default=0, verbose_name='当前库存', db_comment='当前库存（可售）')
    # P0 修复：预占库存（已下单未发货的部分），可用库存 = stock - reserved_stock
    reserved_stock = models.PositiveIntegerField(default=0, verbose_name='预占库存', db_comment='预占库存（待发货订单占用）')
    alert_line = models.PositiveIntegerField(default=50, verbose_name='预警线', db_comment='预警线')
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True, verbose_name='更新时间', db_comment='更新时间')

    class Meta:
        managed = False
        db_table = 'inventory'
        verbose_name = '库存'
        verbose_name_plural = '库存'
        # P1 修复：同一商品只能有一条库存记录
        constraints = [
            models.UniqueConstraint(fields=['product'], name='uniq_inventory_product'),
        ]

    def __str__(self):
        return f"{self.product.name} 库存 {self.stock}（预占 {self.reserved_stock}）"

    @property
    def available_stock(self) -> int:
        """可用库存 = 总库存 - 预占库存"""
        return max(0, (self.stock or 0) - (self.reserved_stock or 0))


# ════════════════════════════════════════════════════════════════
# L5 多智能体编排：商品协调覆盖表（新建托管表，零触碰业务表）
# 营销 Agent(mkt_bot) 通过 /api/coordination/inbound/ 写入这里，
# 商品/库存接口只读此处做覆盖展示，storefront 据此挂「暂不可购」提示。
# ════════════════════════════════════════════════════════════════
class ProductCoordination(models.Model):
    """跨 Agent 协调覆盖：某商品在前台是否暂停购买 + 对客户提示语。

    与 products/inventory 业务表解耦——后者是 managed=False 的历史表，
    这里用一张独立托管表承载「多 Agent 协商后的临时状态」，可随时清除、不污染业务数据。
    """

    product_id = models.IntegerField(db_index=True, unique=True, verbose_name="商品ID")
    purchase_paused = models.BooleanField(default=False, verbose_name="暂停购买")
    customer_notice = models.TextField(blank=True, null=True, verbose_name="客户提示")
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True, verbose_name="更新时间")
    updated_by = models.CharField(max_length=64, blank=True, null=True, verbose_name="更新者")

    class Meta:
        managed = True
        db_table = "product_coordination"
        verbose_name = "商品协调覆盖"
        verbose_name_plural = "商品协调覆盖"

    def __str__(self):
        return f"商品#{self.product_id} 暂停购买={self.purchase_paused}"


class Orders(models.Model):
    # 显式声明 PK 为 INT（匹配 DB 实际列类型 int，DB 是 inspectdb 建的 INT；
    # 若继承 DEFAULT_AUTO_FIELD=BigAutoField 会导致 FK 字段变成 bigint，
    # 与 orders.id(int) 类型不兼容而无法创建外键）。
    id = models.AutoField(primary_key=True)
    order_no = models.CharField(
        max_length=50, unique=True, db_index=True, verbose_name='订单号', db_comment='订单号',
    )
    customer_name = models.CharField(max_length=50, blank=True, null=True, verbose_name='客户姓名', db_comment='客户名')
    phone = models.CharField(max_length=20, blank=True, null=True, db_index=True, verbose_name='联系电话', db_comment='联系电话')
    product = models.ForeignKey(
        Products, models.PROTECT,  # P0 修复：保护式外键，禁止删带订单的产品
        db_column='product_id', null=True, blank=True, verbose_name='关联产品',
        related_name='orders', db_comment='关联产品',
    )
    product_name = models.CharField(max_length=100, blank=True, null=True, verbose_name='产品名称', db_comment='产品名(冗余快照)')
    # P0 修复：商品编码快照（与 product_name 同理：保护历史订单不受产品改名影响）
    product_sku = models.CharField(max_length=32, blank=True, default='', db_index=True, verbose_name='产品SKU', db_comment='产品 SKU 快照')
    # P0 修复：单价快照（与 product_name 同理）
    unit_price = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, verbose_name='下单单价', db_comment='下单时单价')
    # P0 修复：PositiveIntegerField 防负数
    quantity = models.PositiveIntegerField(default=1, verbose_name='数量', db_comment='数量')
    total_price = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, verbose_name='总价', db_comment='总价')
    # P0 修复：状态枚举 + db_index（高频筛选）
    status = models.CharField(
        max_length=20, choices=OrderStatus.choices,
        default=OrderStatus.PENDING, db_index=True, verbose_name='订单状态',
        db_comment='订单状态(未发货/已发货/已完成/退货申请中/已取消/已退货)',
    )
    # 订单归属用户（C 端个人中心「我的订单」依据）：
    #  - 登录状态下单 → 直接写入 user_id（最强归属凭据）
    #  - 历史订单（下单时还没有登录功能）→ user_id 为空，靠 UserProfile.phone 匹配手机号归属
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, models.SET_NULL,
        db_column='user_id', null=True, blank=True,
        verbose_name='下单用户', related_name='orders', db_comment='下单用户(登录用户)',
    )
    ship_company = models.CharField(max_length=50, blank=True, null=True, default='', verbose_name='物流公司', db_comment='物流公司')
    tracking_no = models.CharField(max_length=50, blank=True, null=True, default='', db_index=True, verbose_name='运单号', db_comment='运单号')
    shipped_at = models.DateTimeField(blank=True, null=True, verbose_name='发货时间', db_comment='发货时间')
    # P0 修复：取消/退货状态的时间与原因
    cancelled_at = models.DateTimeField(blank=True, null=True, verbose_name='取消时间', db_comment='取消时间')
    cancel_reason = models.CharField(max_length=200, blank=True, default='', verbose_name='取消/退货原因', db_comment='取消/退货原因')
    # ── 用户侧售后/收货闭环（C 端个人中心 → 后台处理） ──
    completed_at = models.DateTimeField(blank=True, null=True, verbose_name='完成时间', db_comment='用户确认收货时间')
    return_status = models.CharField(
        max_length=20, choices=ReturnStatus.choices, blank=True, default='',
        db_index=True, verbose_name='退货处理结果', db_comment='退货处理结果(待审核/已同意/已拒绝)',
    )
    return_reason = models.CharField(max_length=200, blank=True, default='', verbose_name='退货原因', db_comment='用户填写的退货原因')
    return_requested_at = models.DateTimeField(blank=True, null=True, verbose_name='申请退货时间', db_comment='用户申请退货时间')
    return_handled_at = models.DateTimeField(blank=True, null=True, verbose_name='退货处理时间', db_comment='商家处理退货时间')
    return_note = models.CharField(max_length=200, blank=True, default='', verbose_name='退货处理备注', db_comment='商家处理退货备注/拒绝理由')
    created_at = models.DateTimeField(
        blank=True, null=True, db_index=True, verbose_name='下单时间', db_comment='下单时间',
    )
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True, verbose_name='更新时间', db_comment='更新时间')

    class Meta:
        managed = False
        db_table = 'orders'
        verbose_name = '订单管理'
        verbose_name_plural = '订单管理'
        indexes = [
            # 复合索引：按状态+时间筛选（看板/待发货列表用）
            models.Index(fields=['status', '-created_at'], name='idx_orders_status_created'),
        ]

    def __str__(self):
        return self.order_no


class Conversations(models.Model):
    """对话记录模型 — 前端 AI 聊天的每条消息"""
    # P0 修复：session_id 加 db_index，role 改 choices + 不允许空
    session_id = models.CharField(
        max_length=64, default='', db_index=True, verbose_name='会话ID',
    )
    role = models.CharField(
        max_length=20, choices=ConversationRole.choices,
        default=ConversationRole.USER, verbose_name='角色',
    )
    content = models.TextField(default='', verbose_name='消息内容')
    # P0 修复：created_at 必填 + default + db_index
    created_at = models.DateTimeField(
        default=timezone.now, db_index=True, verbose_name='创建时间',
    )

    class Meta:
        managed = False
        db_table = 'conversations'
        verbose_name = '对话记录'
        verbose_name_plural = '对话记录'
        indexes = [
            # 复合索引：按 session 拉历史（最近 N 条）
            models.Index(fields=['session_id', '-created_at'], name='idx_conv_session_created'),
        ]

    def __str__(self):
        return f"[{self.session_id[:8]}] {self.role}: {self.content[:30]}"


class ContactMessage(models.Model):
    """用户留言模型 — 前端联系表单提交的数据"""
    name = models.CharField(max_length=50, verbose_name='姓名')
    phone = models.CharField(max_length=20, verbose_name='电话', db_index=True)
    email = models.CharField(max_length=100, verbose_name='邮箱', blank=True, default='')
    message = models.TextField(verbose_name='留言内容')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='提交时间', db_index=True)
    # P1 修复：is_read 加索引（看板未读统计快）
    is_read = models.BooleanField(default=False, verbose_name='是否已读', db_index=True)

    class Meta:
        db_table = 'contact_messages'
        verbose_name = '用户留言'
        verbose_name_plural = '用户留言'

    def __str__(self):
        return f"{self.name} ({self.phone}) - {self.created_at}"


class CustomRequest(models.Model):
    """定制需求模型 — 前端定制表单提交的数据"""
    name = models.CharField(max_length=50, verbose_name='姓名')
    phone = models.CharField(max_length=20, verbose_name='电话', db_index=True)
    company = models.CharField(max_length=100, blank=True, verbose_name='公司名称')
    quantity = models.CharField(max_length=50, verbose_name='需求量')
    description = models.TextField(verbose_name='需求描述')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='提交时间', db_index=True)
    # P1 修复：is_read 加索引
    is_read = models.BooleanField(default=False, verbose_name='是否已读', db_index=True)

    class Meta:
        db_table = 'custom_requests'
        verbose_name = '定制需求'
        verbose_name_plural = '定制需求'

    def __str__(self):
        return f"{self.name} ({self.phone}) - {self.created_at}"


# ════════════════════════════════════════════════════════════════
# 余额管理（让"钱从哪里来到哪里去"在后台可追溯）
#   - Wallet：公司钱包（单例）
#   - Transaction：收支流水（订单收入/退款/提现/手动调账）
#   - 订单已发货自动记「订单收入」；已退货自动记「订单退款」
# ════════════════════════════════════════════════════════════════
class TxType(models.TextChoices):
    """流水方向"""
    INCOME  = "收入", "收入"
    EXPENSE = "支出", "支出"


class TxCategory(models.TextChoices):
    """流水分类"""
    ORDER_INCOME  = "订单收入", "订单收入"
    ORDER_REFUND  = "订单退款", "订单退款"
    WITHDRAW      = "提现",     "提现"
    MANUAL        = "手动调账", "手动调账"
    OTHER         = "其他",     "其他"


class Wallet(models.Model):
    """公司钱包（始终只保留 id=1 一条记录）"""
    balance = models.DecimalField(
        max_digits=14, decimal_places=2, default=0,
        verbose_name='当前余额',
        help_text='所有收入（+）减所有支出（-）的累计结果',
    )
    updated_at = models.DateTimeField(auto_now=True, verbose_name='更新时间')

    class Meta:
        db_table = 'company_wallet'
        verbose_name = '公司钱包'
        verbose_name_plural = '公司钱包'

    def __str__(self):
        return f"钱包余额 ¥{self.balance:,.2f}"

    @classmethod
    def get_solo(cls):
        """始终返回 id=1 的一条记录（不存在则自动创建）"""
        obj, _ = cls.objects.get_or_create(pk=1, defaults={"balance": 0})
        return obj


class Transaction(models.Model):
    """收支流水（每一笔账都必须有据可查）"""
    wallet = models.ForeignKey(
        Wallet, on_delete=models.PROTECT, related_name='transactions',
        verbose_name='钱包',
    )
    tx_type = models.CharField(
        max_length=10, choices=TxType.choices,
        verbose_name='类型',
    )
    category = models.CharField(
        max_length=20, choices=TxCategory.choices,
        verbose_name='分类',
    )
    amount = models.DecimalField(
        max_digits=14, decimal_places=2,
        verbose_name='金额',
        help_text='正数；通过 tx_type 决定是收入还是支出',
    )
    order = models.ForeignKey(
        Orders, on_delete=models.SET_NULL,
        null=True, blank=True, related_name='transactions',
        verbose_name='关联订单',
    )
    note = models.CharField(
        max_length=200, blank=True, default='',
        verbose_name='备注',
    )
    operator = models.ForeignKey(
        'auth.User', on_delete=models.SET_NULL,
        null=True, blank=True, related_name='+',
        verbose_name='操作人',
    )
    created_at = models.DateTimeField(
        auto_now_add=True, db_index=True,
        verbose_name='时间',
    )

    class Meta:
        db_table = 'wallet_transactions'
        verbose_name = '收支流水'
        verbose_name_plural = '收支流水'
        ordering = ('-created_at',)
        indexes = [
            models.Index(fields=['tx_type', '-created_at'], name='idx_tx_type_time'),
            models.Index(fields=['category', '-created_at'], name='idx_tx_cat_time'),
        ]

    def __str__(self):
        sign = '+' if self.tx_type == TxType.INCOME else '-'
        return f"{sign}¥{self.amount} · {self.category} · {self.created_at:%Y-%m-%d %H:%M}"


# ════════════════════════════════════════════════════════════════
# 用户资料（C 端个人中心）
# ════════════════════════════════════════════════════════════════
# 为什么不直接改 auth_user：
#   auth_user 由 Django 管理，往里塞业务列会让 migrate 的模型状态与 DB 不一致。
#   这里用一张独立表挂 OneToOne，既不动框架表，又能扩展字段。
#
# phone 的核心作用：**关联历史订单**。
#   订单表里只有 phone（当时还没有登录功能），所以注册用户绑定手机号后，
#   就能在个人中心看到「用这个手机号下过的历史订单」。
#   为保证归属唯一，绑定时会校验该手机号未被其它账号占用。
# ════════════════════════════════════════════════════════════════
class UserProfile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, models.CASCADE,
        primary_key=True, verbose_name='用户', related_name='profile',
    )
    phone = models.CharField(
        max_length=20, blank=True, default='', db_index=True,
        verbose_name='绑定手机号',
        help_text='绑定后可在个人中心看到该手机号下的历史订单',
    )
    nickname = models.CharField(
        max_length=50, blank=True, default='', verbose_name='收货人姓名',
        help_text='下单页会自动带入，可随时修改',
    )
    updated_at = models.DateTimeField(auto_now=True, verbose_name='更新时间')

    class Meta:
        db_table = 'user_profile'
        verbose_name = '用户资料'
        verbose_name_plural = '用户资料'

    def __str__(self):
        return f'{self.user.username}｜{self.phone or "未绑定手机号"}'
